export interface Insurer {
  id: string;
  name: string;
  logo: string;
  tagline: string;
  color: string;
  rating: number;
  reviews: number;
  appRating: number;
  animals: string[];
  monthlyPrice: Record<string, number>;
  deductible: string;
  reimbursement: string;
  maxAnnual: string;
  waitingPeriod: string;
  features: string[];
  notCovered: string[];
  contact: {
    phone: string;
    website: string;
    email: string;
  };
  claimsTime: string;
}

export const insurers: Insurer[] = [
  {
    id: "pawguard-premium",
    name: "PawGuard Premium",
    logo: "🛡️",
    tagline: "Premium coverage for pets that deserve the best",
    color: "#1E3A8A",
    rating: 4.9,
    reviews: 12847,
    appRating: 4.8,
    animals: ["dog", "cat", "bird", "rabbit", "reptile", "exotic"],
    monthlyPrice: { dog: 89, cat: 64, bird: 52, rabbit: 48, reptile: 55, exotic: 72 },
    deductible: "$100–$500",
    reimbursement: "90%",
    maxAnnual: "Unlimited",
    waitingPeriod: "3 days illness / 1 day accident",
    features: [
      "Unlimited annual coverage",
      "90% reimbursement on all claims",
      "Hereditary condition coverage",
      "Chronic illness lifetime coverage",
      "Emergency vet visit coverage",
      "Specialist & specialist referrals",
      "24/7 vet telehealth hotline",
      "Prescription medication coverage",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Cosmetic procedures",
      "Breeding & pregnancy costs",
      "Experimental treatments",
    ],
    contact: {
      phone: "1-800-729-4827",
      website: "https://pawguardpremium.example.com",
      email: "support@pawguardpremium.example.com",
    },
    claimsTime: "2–3 business days",
  },
  {
    id: "budget-paws",
    name: "BudgetPaws",
    logo: "🐾",
    tagline: "Affordable protection for every pet owner",
    color: "#16A34A",
    rating: 4.1,
    reviews: 8231,
    appRating: 3.9,
    animals: ["dog", "cat"],
    monthlyPrice: { dog: 19, cat: 14, bird: 0, rabbit: 0, reptile: 0, exotic: 0 },
    deductible: "$250–$1000",
    reimbursement: "70%",
    maxAnnual: "$3,000",
    waitingPeriod: "14 days illness / 3 days accident",
    features: [
      "Low monthly premiums",
      "Accident & illness coverage",
      "Emergency hospitalization",
      "X-rays and diagnostics",
      "Surgery coverage",
      "Cancer treatment (basic)",
      "Dental illness coverage",
      "Online claims submission",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Hereditary conditions",
      "Wellness & preventive care",
      "Behavioral therapy",
    ],
    contact: {
      phone: "1-888-283-7297",
      website: "https://budgetpaws.example.com",
      email: "hello@budgetpaws.example.com",
    },
    claimsTime: "7–10 business days",
  },
  {
    id: "exotic-shield",
    name: "ExoticShield",
    logo: "🦎",
    tagline: "The specialist in exotic & unusual companion coverage",
    color: "#7C3AED",
    rating: 4.7,
    reviews: 3102,
    appRating: 4.6,
    animals: ["bird", "rabbit", "reptile", "exotic"],
    monthlyPrice: { dog: 0, cat: 0, bird: 38, rabbit: 35, reptile: 42, exotic: 58 },
    deductible: "$150–$400",
    reimbursement: "80%",
    maxAnnual: "$10,000",
    waitingPeriod: "5 days illness / 1 day accident",
    features: [
      "Specialist exotic vet network",
      "Avian & reptile surgery coverage",
      "Behavioral enrichment therapy",
      "Species-specific illness coverage",
      "Parasite & infection treatment",
      "Lab work & diagnostic imaging",
      "End-of-life care covered",
      "Multi-pet exotic discount",
    ],
    notCovered: [
      "Wild-caught or undomesticated animals",
      "Pre-existing conditions",
      "Breeding expenses",
      "Food & habitat costs",
    ],
    contact: {
      phone: "1-877-396-4274",
      website: "https://exoticshield.example.com",
      email: "claims@exoticshield.example.com",
    },
    claimsTime: "4–5 business days",
  },
  {
    id: "wellness-first",
    name: "WellnessFirst",
    logo: "💚",
    tagline: "Prevention is the best medicine — we cover it all",
    color: "#059669",
    rating: 4.6,
    reviews: 9754,
    appRating: 4.7,
    animals: ["dog", "cat", "rabbit"],
    monthlyPrice: { dog: 72, cat: 55, bird: 0, rabbit: 44, reptile: 0, exotic: 0 },
    deductible: "$100–$300",
    reimbursement: "80%",
    maxAnnual: "$15,000",
    waitingPeriod: "7 days illness / 0 days accident",
    features: [
      "Annual wellness exam covered",
      "Vaccinations & boosters",
      "Flea, tick & heartworm prevention",
      "Dental cleanings covered",
      "Spay/neuter reimbursement",
      "Nutritional counseling",
      "Microchipping covered",
      "Chronic disease management",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Cosmetic procedures",
      "Experimental treatments",
      "Grooming & boarding",
    ],
    contact: {
      phone: "1-800-935-5556",
      website: "https://wellnessfirst.example.com",
      email: "care@wellnessfirst.example.com",
    },
    claimsTime: "3–5 business days",
  },
  {
    id: "rapidclaim",
    name: "RapidClaim",
    logo: "⚡",
    tagline: "Fast claims, fewer headaches, happier pets",
    color: "#D97706",
    rating: 4.5,
    reviews: 6421,
    appRating: 4.8,
    animals: ["dog", "cat", "bird"],
    monthlyPrice: { dog: 55, cat: 42, bird: 46, rabbit: 0, reptile: 0, exotic: 0 },
    deductible: "$200–$500",
    reimbursement: "80%",
    maxAnnual: "$8,000",
    waitingPeriod: "5 days illness / 0 days accident",
    features: [
      "Same-day direct vet payments",
      "AI-powered claims processing",
      "In-app claims tracking",
      "No paperwork required",
      "Emergency boarding coverage",
      "Lost pet advertising costs",
      "Accident-only plan option",
      "Flexible deductible options",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Preventive & wellness care",
      "Pregnancy & whelping",
      "Parasites (preventable)",
    ],
    contact: {
      phone: "1-866-472-7253",
      website: "https://rapidclaim.example.com",
      email: "fasthelp@rapidclaim.example.com",
    },
    claimsTime: "24 hours",
  },
  {
    id: "multispecies",
    name: "MultiPet Pro",
    logo: "🌟",
    tagline: "One policy, every species — simplified",
    color: "#0891B2",
    rating: 4.4,
    reviews: 5187,
    appRating: 4.3,
    animals: ["dog", "cat", "bird", "rabbit", "reptile", "exotic"],
    monthlyPrice: { dog: 62, cat: 48, bird: 43, rabbit: 38, reptile: 46, exotic: 61 },
    deductible: "$200–$600",
    reimbursement: "80%",
    maxAnnual: "$10,000",
    waitingPeriod: "10 days illness / 2 days accident",
    features: [
      "Multi-pet household discount",
      "All species on one policy",
      "Bundled billing options",
      "Illness & accident combined",
      "Specialist referral network",
      "Cancer treatment included",
      "Orthopedic surgery coverage",
      "Behavioral therapy included",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Wild or exotic unlicensed animals",
      "Elective surgeries",
      "Nutritional supplements",
    ],
    contact: {
      phone: "1-844-685-4768",
      website: "https://multipetpro.example.com",
      email: "info@multipetpro.example.com",
    },
    claimsTime: "3–4 business days",
  },
  {
    id: "senior-paws",
    name: "SeniorPaws",
    logo: "🐕",
    tagline: "Specialized coverage for the golden years",
    color: "#B45309",
    rating: 4.3,
    reviews: 4322,
    appRating: 4.1,
    animals: ["dog", "cat"],
    monthlyPrice: { dog: 110, cat: 88, bird: 0, rabbit: 0, reptile: 0, exotic: 0 },
    deductible: "$100–$250",
    reimbursement: "90%",
    maxAnnual: "$20,000",
    waitingPeriod: "7 days illness / 1 day accident",
    features: [
      "No age cap on enrollment",
      "Arthritis & joint care covered",
      "Cognitive dysfunction coverage",
      "Heart disease management",
      "Palliative care included",
      "Bi-annual senior wellness exam",
      "Pain management medications",
      "In-home vet visit coverage",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Elective cosmetic procedures",
      "Breeding & pregnancy",
      "Over-the-counter supplements",
    ],
    contact: {
      phone: "1-800-736-7297",
      website: "https://seniorpaws.example.com",
      email: "seniors@seniorpaws.example.com",
    },
    claimsTime: "2–3 business days",
  },
  {
    id: "aqua-avian",
    name: "AquaAvian",
    logo: "🦜",
    tagline: "From parrots to parakeets — fully feathered coverage",
    color: "#0E7490",
    rating: 4.2,
    reviews: 1875,
    appRating: 4.0,
    animals: ["bird", "exotic"],
    monthlyPrice: { dog: 0, cat: 0, bird: 28, rabbit: 0, reptile: 0, exotic: 45 },
    deductible: "$100–$300",
    reimbursement: "80%",
    maxAnnual: "$5,000",
    waitingPeriod: "5 days illness / 1 day accident",
    features: [
      "Avian specialist network access",
      "Wing & feather condition coverage",
      "Psittacosis & viral coverage",
      "Surgical & anesthesia costs",
      "Nutritional deficiency treatment",
      "Egg binding treatment",
      "Beak & nail injury coverage",
      "Annual avian wellness exam",
    ],
    notCovered: [
      "Pre-existing feather conditions",
      "Wild-caught birds",
      "Habitat & cage accessories",
      "Breeding & egg incubation",
    ],
    contact: {
      phone: "1-877-278-2846",
      website: "https://aquaavian.example.com",
      email: "chirp@aquaavian.example.com",
    },
    claimsTime: "5–6 business days",
  },
];

export const ANIMAL_TYPES = [
  { id: "all", label: "All", icon: "🐾" },
  { id: "dog", label: "Dog", icon: "🐕" },
  { id: "cat", label: "Cat", icon: "🐈" },
  { id: "bird", label: "Bird", icon: "🦜" },
  { id: "rabbit", label: "Rabbit", icon: "🐇" },
  { id: "reptile", label: "Reptile", icon: "🦎" },
  { id: "exotic", label: "Exotic", icon: "✨" },
];
